//! qBittorrent tool surface.
//!
//! Endpoint registry: `qbittorrent.{list, detail, create, update, delete}` —
//! generated by `#[endpoint_resource]`.
//!
//! WebUI tools:
//!   - `qbittorrent.listen_port.status`  listen/announce ports, reachability, match against an expected port
//!   - `qbittorrent.listen_port.sync`    converge the listen or announce port on a target (dry run by default)

use plugin_toolkit::prelude::*;

use crate::execute;
use crate::listen_port::{self, ListenPortStatus, ListenPortSync, Mode, WebUi};

#[endpoint_resource(plugin = "qbittorrent")]
pub struct QbittorrentEndpoint {
    pub name: String,
    pub username: String,
    #[secret]
    pub password: String,
    pub enabled: bool,
}

async fn connect(name: &str) -> Result<WebUi> {
    let row = endpoint_db::require(name)?;
    let password = plugin_toolkit::secrets::resolve_scoped(
        "qbittorrent",
        name,
        "password",
        (!row.password.is_empty()).then_some(row.password.as_str()),
    )?;
    let base_url = route::resolve_reachable(name, &row.routes, false).await?;
    WebUi::login(&base_url, &row.username, &password).await
}

#[orca_struct(args)]
pub struct ListenPortStatusArgs {
    /// Registered qbittorrent endpoint name.
    #[arg(long)]
    pub name: String,
    /// Which port `expected_port` is compared with: `announce` (reported to
    /// trackers) or `listen`.
    #[arg(long, value_enum, default_value_t = Mode::Announce)]
    #[serde(default)]
    pub mode: Mode,
    /// Port the selected mode should carry. Omitted, `matches` is absent.
    #[arg(long)]
    #[serde(default)]
    pub expected_port: Option<u16>,
}

/// Read qBittorrent's BitTorrent listen and announce ports, libtorrent version
/// and whether `announce_port` takes effect, connection status
/// (`connected`/`firewalled`/`disconnected`), and whether the selected mode's
/// port matches `expected_port`. In listen mode on libtorrent before 2.0.11,
/// `leftover_announce_port` reports a non-zero `announce_port` that trackers do
/// not hear yet: `matches` stays true, but `listen_port.sync` still clears it
/// because it takes effect once qBittorrent is upgraded.
#[orca_tool(domain = "qbittorrent", verb = "listen_port.status", role = "any")]
async fn qbittorrent_listen_port_status(
    args: ListenPortStatusArgs,
    _ctx: &ToolCtx,
) -> Result<ListenPortStatus> {
    let ui = connect(&args.name).await?;
    listen_port::status(&ui, args.mode, args.expected_port).await
}

#[orca_struct(args)]
pub struct ListenPortSyncArgs {
    /// Registered qbittorrent endpoint name.
    #[arg(long)]
    pub name: String,
    /// `announce` sets the port reported to trackers and leaves the listen port
    /// alone (a NAT maps the VPN port onto it); `listen` sets the listen port.
    #[arg(long, value_enum, default_value_t = Mode::Announce)]
    #[serde(default)]
    pub mode: Mode,
    /// Target port, normally the VPN forwarded port. Exclusive with
    /// `port_file`.
    #[arg(long)]
    #[serde(default)]
    pub port: Option<u16>,
    /// File holding the port, read on the host running this plugin, e.g.
    /// gluetun's `forwarded_port` with `--mode listen` (gluetun forwards the
    /// port unmapped). Exclusive with `port`.
    #[arg(long)]
    #[serde(default)]
    pub port_file: Option<String>,
    /// Apply. Omitted, reports drift and changes nothing.
    #[arg(long)]
    #[serde(default)]
    pub execute: bool,
}

/// **Sync the port**: in `announce` mode (default) set the port reported to
/// trackers (`announce_port`, qBittorrent 5.1+ built on libtorrent 2.0.11+);
/// in `listen` mode set the listen port and reset `announce_port` to `0`.
/// `random_port` counts as drift in both. Idempotent; writes only on drift.
/// Without `execute`, reports drift and any refusal, and changes nothing.
#[orca_tool(
    domain = "qbittorrent",
    verb = "listen_port.sync",
    role = "admin",
    execute_gated = false
)]
async fn qbittorrent_listen_port_sync(
    args: ListenPortSyncArgs,
    ctx: &ToolCtx,
) -> Result<ListenPortSync> {
    const TOOL: &str = "qbittorrent.listen_port.sync";
    execute::require_admin(TOOL, ctx)?;
    let target = listen_port::target_port(args.port, args.port_file.as_deref())?;
    let ui = connect(&args.name).await?;
    listen_port::sync(&ui, args.mode, target, args.execute).await
}

#[cfg(test)]
mod tests {
    use super::*;
    use plugin_toolkit::contract::config::{Config, Model, Ports};
    use plugin_toolkit::contract::CallerIdentity;
    use std::sync::{Arc, OnceLock};

    /// The toolkit already sandboxes orca state under `cargo test`; the ctx
    /// paths point at a tempdir too.
    fn ctx() -> ToolCtx {
        static HOME: OnceLock<tempfile::TempDir> = OnceLock::new();
        let home = HOME.get_or_init(|| tempfile::tempdir().unwrap()).path();
        ToolCtx::new(Arc::new(Config {
            anthropic_api_key: None,
            lmstudio_url: String::new(),
            ollama_url: String::new(),
            default_model: Model::LMStudio {
                id: String::new(),
                url: String::new(),
            },
            app_dir: home.to_path_buf(),
            memory_root: home.to_path_buf(),
            db_path: home.join("orca.db"),
            ports: Ports::default(),
        }))
    }

    #[tokio::test]
    async fn sync_refuses_non_admins_before_touching_the_endpoint() {
        let user = CallerIdentity {
            user_id: "u".into(),
            username: "op".into(),
            role: "user".into(),
            can_mutate: true,
        };
        for (ctx, want) in [
            (ctx(), "no caller identity"),
            (ctx().with_auth(user), "requires role 'admin'"),
        ] {
            let args = ListenPortSyncArgs {
                name: "dl".into(),
                mode: Mode::Listen,
                port: Some(51234),
                port_file: None,
                execute: false,
            };
            let err = qbittorrent_listen_port_sync(args, &ctx).await.unwrap_err();
            assert!(err.to_string().contains(want), "{err}");
        }
    }
}
