//! qBittorrent tool surface.
//!
//! Endpoint registry: `qbittorrent.{list, detail, create, update, delete}` —
//! generated by `#[endpoint_resource]`.
//!
//! WebUI tools:
//!   - `qbittorrent.listen_port.status`  listen/announce ports, reachability, match against an expected port
//!   - `qbittorrent.listen_port.sync`    converge the listen or announce port on a target (dry run by default)

use plugin_toolkit::prelude::*;

use crate::execute;
use crate::listen_port::{self, ListenPortStatus, ListenPortSync, Mode, WebUi};

#[endpoint_resource(plugin = "qbittorrent")]
pub struct QbittorrentEndpoint {
    pub name: String,
    pub username: String,
    #[secret]
    pub password: String,
    pub enabled: bool,
}

async fn connect(name: &str) -> Result<WebUi> {
    let row = endpoint_db::require(name)?;
    let password = plugin_toolkit::secrets::resolve_scoped(
        "qbittorrent",
        name,
        "password",
        (!row.password.is_empty()).then_some(row.password.as_str()),
    )?;
    let base_url = route::resolve_reachable(name, &row.routes, false).await?;
    WebUi::login(&base_url, &row.username, &password).await
}

#[orca_struct(args)]
pub struct ListenPortStatusArgs {
    /// Registered qbittorrent endpoint name.
    #[arg(long)]
    pub name: String,
    /// Which port `expected_port` is compared with: `announce` (reported to
    /// trackers) or `listen`.
    #[arg(long, value_enum, default_value_t = Mode::Announce)]
    #[serde(default)]
    pub mode: Mode,
    /// Port the selected mode should carry. Omitted, `matches` is absent.
    #[arg(long)]
    #[serde(default)]
    pub expected_port: Option<u16>,
}

/// Read qBittorrent's BitTorrent listen and announce ports and connection
/// status (`connected`/`firewalled`/`disconnected`), and whether the selected
/// mode's port matches `expected_port`.
#[orca_tool(domain = "qbittorrent", verb = "listen_port.status", role = "any")]
async fn qbittorrent_listen_port_status(
    args: ListenPortStatusArgs,
    _ctx: &ToolCtx,
) -> Result<ListenPortStatus> {
    let ui = connect(&args.name).await?;
    listen_port::status(&ui, args.mode, args.expected_port).await
}

#[orca_struct(args)]
pub struct ListenPortSyncArgs {
    /// Registered qbittorrent endpoint name.
    #[arg(long)]
    pub name: String,
    /// `announce` sets the port reported to trackers and leaves the listen port
    /// alone (a NAT maps the VPN port onto it); `listen` sets the listen port.
    #[arg(long, value_enum, default_value_t = Mode::Announce)]
    #[serde(default)]
    pub mode: Mode,
    /// Target port, normally the VPN forwarded port. Exclusive with
    /// `port_file`.
    #[arg(long)]
    #[serde(default)]
    pub port: Option<u16>,
    /// File holding the port (e.g. gluetun's `forwarded_port`), read on the
    /// host running this plugin. Exclusive with `port`.
    #[arg(long)]
    #[serde(default)]
    pub port_file: Option<String>,
    /// Apply. Omitted, reports drift and changes nothing.
    #[arg(long)]
    #[serde(default)]
    pub execute: bool,
}

/// **Sync the port**: in `announce` mode (default) set the port reported to
/// trackers (`announce_port`, qBittorrent 5.1+); in `listen` mode set the
/// listen port. `random_port` counts as drift in both. Idempotent; writes only
/// on drift. Without `execute`, reports drift and changes nothing.
#[orca_tool(
    domain = "qbittorrent",
    verb = "listen_port.sync",
    role = "admin",
    execute_gated = false
)]
async fn qbittorrent_listen_port_sync(
    args: ListenPortSyncArgs,
    ctx: &ToolCtx,
) -> Result<ListenPortSync> {
    const TOOL: &str = "qbittorrent.listen_port.sync";
    execute::require_admin(TOOL, ctx)?;
    let target = listen_port::target_port(args.port, args.port_file.as_deref())?;
    let ui = connect(&args.name).await?;
    listen_port::sync(&ui, args.mode, target, args.execute).await
}
