//! qBittorrent tool surface.
//!
//! Endpoint registry: `qbittorrent.{list, detail, create, update, delete}` —
//! generated by `#[endpoint_resource]`.
//!
//! WebUI tools:
//!   - `qbittorrent.listen_port.status`  listen port, reachability, match against an expected port
//!   - `qbittorrent.listen_port.sync`    converge the listen port on a target (dry run by default)

use plugin_toolkit::prelude::*;

use crate::execute;
use crate::listen_port::{self, ListenPortStatus, ListenPortSync, WebUi};

#[endpoint_resource(plugin = "qbittorrent")]
pub struct QbittorrentEndpoint {
    pub name: String,
    pub username: String,
    #[secret]
    pub password: String,
    pub enabled: bool,
}

async fn connect(name: &str) -> Result<WebUi> {
    let row = endpoint_db::require(name)?;
    let password = plugin_toolkit::secrets::resolve_scoped(
        "qbittorrent",
        name,
        "password",
        (!row.password.is_empty()).then_some(row.password.as_str()),
    )?;
    let base_url = route::resolve_reachable(name, &row.routes, false).await?;
    WebUi::login(&base_url, &row.username, &password).await
}

#[orca_struct(args)]
pub struct ListenPortStatusArgs {
    /// Registered qbittorrent endpoint name.
    #[arg(long)]
    pub name: String,
    /// Port the client should listen on (the VPN forwarded port, or the
    /// internal port of a fixed NAT mapping). Omitted, `matches` is absent.
    #[arg(long)]
    #[serde(default)]
    pub expected_port: Option<u16>,
}

/// Read qBittorrent's BitTorrent listen port and connection status
/// (`connected`/`firewalled`/`disconnected`), and whether the port matches
/// `expected_port`.
#[orca_tool(domain = "qbittorrent", verb = "listen_port.status", role = "any")]
async fn qbittorrent_listen_port_status(
    args: ListenPortStatusArgs,
    _ctx: &ToolCtx,
) -> Result<ListenPortStatus> {
    let ui = connect(&args.name).await?;
    listen_port::status(&ui, args.expected_port).await
}

#[orca_struct(args)]
pub struct ListenPortSyncArgs {
    /// Registered qbittorrent endpoint name.
    #[arg(long)]
    pub name: String,
    /// Port to listen on: the VPN forwarded port, or the internal port of a
    /// fixed NAT mapping. Exclusive with `port_file`.
    #[arg(long)]
    #[serde(default)]
    pub port: Option<u16>,
    /// File holding the port (e.g. gluetun's `forwarded_port`), read on the
    /// host running this plugin. Exclusive with `port`.
    #[arg(long)]
    #[serde(default)]
    pub port_file: Option<String>,
    /// Apply. Omitted, reports drift and changes nothing.
    #[arg(long)]
    #[serde(default)]
    pub execute: bool,
}

/// **Sync the listen port**: set qBittorrent's BitTorrent listen port to the
/// target and turn off `random_port`. Idempotent; writes only on drift.
/// Without `execute`, reports drift and changes nothing.
#[orca_tool(
    domain = "qbittorrent",
    verb = "listen_port.sync",
    role = "admin",
    execute_gated = false
)]
async fn qbittorrent_listen_port_sync(
    args: ListenPortSyncArgs,
    ctx: &ToolCtx,
) -> Result<ListenPortSync> {
    const TOOL: &str = "qbittorrent.listen_port.sync";
    execute::require_admin(TOOL, ctx)?;
    let target = listen_port::target_port(args.port, args.port_file.as_deref())?;
    let ui = connect(&args.name).await?;
    listen_port::sync(&ui, target, args.execute).await
}
